; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c3_supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
board = esp32-c3-devkitm-1 ; 官方選單沒有 SuperMini，用 DevKitM-1 核心板定義完美相容
framework = arduino

; 🚨 核心死穴：如果不加這兩行，你的 Serial.print() 將永遠不會輸出到電腦上！
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200

lib_extra_dirs = ~/Documents/Arduino/libraries
